### ISSUE TITLE
Avoid Json showing up?

### ISSUE THREAD

**Issue by luixal** [VeliovGroup/Meteor-logger-console#2]
Hi,

Is there anyway to avoid json data to be shown in console? I'm using logger-mongo, logger-file and logger-console (yeah, I know, what a f*****g paranoid) and it's great to have that data saved in the mongo collection, but it's becoming a problem to have it shown in the console also.

Any option to avoid it?

Thanks!

**Comment by dr-dimitru** [comment]
To hide it on client - set client option to false in enable() method.
If you want to hide on the server - not currently possible, and it's kinda weird to collapse data you're waiting for.
Maybe you want to stop using logger-console and stay only with file and mongo?

**Comment by luixal** [comment]
Maybe I didn't explain properly what I'm trying to do: I don't care about logging in the client's console, I was talking about the logs shown in the server console. I want to keep them, but avoid showing the additional data as JSON.

This is, when I log something (in the server) like:

``` javascript
log.info('login from user ' + userId, {data: user});
```

I want the message (login from user XXXXX) to show up in the server console, but not the additional user data (which is shown in JSON). BUT, I want to keep it in the mongo collection.

Maybe another option like:

``` javascript
this.log = new Logger();
(new LoggerConsole(log)).enable({
  enable: true,
  client: true, /* Output logs on both Server's and Client's console */
  server: true  /* Calls from Client and Server will be executed on Server */
  showAdditional: false /* allows me to avoid showing additional json on console */
});

(new LoggerMongo(log)).enable({
  enable: true,
  client: true, /* Output logs on both Server's and Client's console */
  server: true  /* Calls from Client and Server will be executed on Server */
  showAdditional: true /* allows me to keep additional data in mongo collection */
});
```

is what I'm trying to find.

Not sure if this can be done... and I know I'm posting a lot of FR/issues this days, but your packages are the best fit to me for keeping my app logs :)

Thanks!

**Comment by dr-dimitru** [comment]
I got you.
It will require additional package update. Then you will be able to do something like:

``` js
this.log = new Logger();
var LogConsole = new LoggerConsole(log);
LogConsole.enable({
  enable: true,
  client: true, /* Output logs on both Server's and Client's console */
  server: true  /* Calls from Client and Server will be executed on Server */
});

var LogMongo = new LoggerMongo(log);
LogMongo.enable({
  enable: true,
  client: true, /* Output logs on both Server's and Client's console */
  server: true  /* Calls from Client and Server will be executed on Server */
});

LogConsole.info('login from user ' + userId, {data: userId}); /* this will output only {data: 'xxx'} to server */
LogMongo.info('login from user ' + userId, {data: user});  /* this will put full object to MongoDB */
```

You will have to call two different `.info()` methods, but it will do what you want, will it work for you?

**Comment by luixal** [comment]
Hmm... I think we have different things in mind, but maybe your idea is better than mine.

I didn't thought about using two different loggers (`LogConsole` or `LogMongo`), since the call itself is the same, with the same params (`javascript .info('login from user ' + userId, {data: userId});`).

I was thinking more about a prop to tell each... "transport" (?) something like: 'ey, you're showing additional data' or 'nope, you just show the message, don't fill console output with the additional data'.

So, the way I thought about it was this:
- Configure that prop when setting the console logger:

``` javascript
new LoggerConsole(log).enable({
  enable: true,
  client: true, /* Output logs on both Server's and Client's console */
  server: true  /* Calls from Client and Server will be executed on Server */
  logAdditionalData: false
});
```
- Configure that same prop when setting the mongo/file logger:

``` javascript
new LoggerConsole(log).enable({
  enable: true,
  client: true, /* Output logs on both Server's and Client's console */
  server: true  /* Calls from Client and Server will be executed on Server */
  logAdditionalData: true
});
```
- Use the logger as usual:

``` javascript
logger.info('my message', {data: userId});
```

Then, each "transport" will internally follow its config in order to log the additional data or not. In the example, console logger won't log the additional data, but mongo logger will.

Makes sense to you? Maybe the package is working in other way under the hood.

**Comment by dr-dimitru** [comment]
The way I explained is planned further development. And the only way we can unify different behaviours for each adapter.

**Comment by dr-dimitru** [comment]
@luixal anyways, let me know what do you think, what is best solution for you, and why.

**Comment by luixal** [comment]
Hi @dr-dimitru , sorry for the delay, I got plenty of things to deliver and I've been full of work :(

I've been thinking about this, and reviewing the logs I've gathered, I found two annoying things:
- **logger-console** is always showing up the additional data, which makes it not so useful (I store big objects, sometimes one log entry eats up all my console buffer so I can't see any previous log).
- **logger-file** is not showing that additional data, which would be great for me.
- **logger-mongo** is just great for me, although I've added some things

Maybe, the quickest solution that will cover all this issues (and maybe more, as it would provide a more granular control over the logs if the user needs to) would be allowing the user to set a custom function for modifying/creating the log object.

I would apply that function like this (for each case I've commented above):
- **logger-console**: i would remove the additional data property from the log object. I would change the format (no worries, default format is great, but someone could just like a different one).
- **logger-file**: i would just keep the full object, additional data included. I would also change the format, i.e to CSV so I can load that file in an analyzer.
- **logger-mongo**: I would keep the full object.

As a first approach, I'm imaging something like this (for logger-console):

``` javascript
new LoggerConsole(log).enable({
  enable: true,
  client: true, /* Output logs on both Server's and Client's console */
  server: true  /* Calls from Client and Server will be executed on Server */
  customOutput: function(origin, log) {
    return '[' + log.level + ']' +
      moment(log.date).format('[DD/MM/YYYY][HH:mm]') +
      '[' + message + ']' +
      '[' + origin + ']' +
      '[' + log.userId + ']' +
      '[Additional ' + log.additional ? 'TRUE' : 'FALSE' + ']';
  }
});
```

that would print out in my console only this, without all the json data:

```
[WARN][28/05/2016][client][adF34sdfed11ef][warning log][Additional TRUE]
```

in the case of logger-fiile, I would use something like this:

``` javascript
new LoggerConsole(log).enable({
  enable: true,
  client: true, /* Output logs on both Server's and Client's console */
  server: true  /* Calls from Client and Server will be executed on Server */
  customOutput: function(origin, log) {
    return '[' + log.level + ']' +
      moment(log.date).format('[DD/MM/YYYY][HH:mm]') +
      '[' + message + ']' +
      '[' + origin + ']' +
      '[' + log.userId + ']' +
      '[' + JSON.stringify(log.additional) + ']';
  }
});
```

that would save in the file the same info, but with the additional object parsed as JSON.

What do you think? Maybe this approach is better than adding options (although they can be complementary).

**Comment by dr-dimitru** [comment]
> logger-console is always showing up the additional data, which makes it not so useful (I s....

I agree with this list, we can fix/enhance it.

> allowing the user to set a custom function for modifying/creating the log object.

Partly implemented in [`ostrio:logger file`](https://github.com/VeliovGroup/Meteor-Files/stargazers) in `options.format`.

> i would just keep the full object, additional data included. I would also change the format, i.e to CSV so I can load that file in an analyzer.

Again, its partly implemented in [`ostrio:logger file`](https://github.com/VeliovGroup/Meteor-Files/stargazers) in `options.format`.

Let me know if `format` callback is works for you, so I'll add similar implementation in two other log adapters.

**Comment by luixal** [comment]
Hi! A busy week again :'(

Yes, I had already seen the ostrio:logger package and the format function and it achieves what I was talking about.

Would be great to have it in this package :)

**Comment by dr-dimitru** [comment]
Hi @luixal 
Implemented in v1.2.0, please update and let me know how it works for you

**Comment by luixal** [comment]
Hi @dr-dimitru ,

Maybe I haven't done it right, but it seems to work for some levels only. This is my code:

``` javascript
new LoggerConsole(
  logger,
  {
    format: function(opts) {
      var res = '[' + opts.level + ']';
      res += '[' + moment(opts.time).format('DD/MM/YYYY HH:mm') + ']';
      res += (Meteor.isServer) ? '[SERVER]' : '[CLIENT]';
      if (opts.userId) res += '[' + opts.userId + ']';
      res += '[' + opts.message + ']';
      if (opts.data) res += '[+]';
      return res;
    }
  }
).enable();
```

and this is the output shown on the console:

```
I20160612-19:11:50.104(2)?   [DEBUG][12/06/2016 19:11][SERVER][Server started][+]  
I20160612-19:11:50.109(2)?  [ERROR][12/06/2016 19:11][SERVER][Error starting JobServer. No configuration found.][+] 
=> Started your app.
=> App running at: http://localhost:3000/
I20160612-19:11:56.310(2)?  [INFO][12/06/2016 19:11][SERVER][rtMZfy2ApCsnmw9vg][login][+] 
I20160612-19:11:56.310(2)? {
I20160612-19:11:56.311(2)?   "data": {
I20160612-19:11:56.311(2)?     "type": "resume",
I20160612-19:11:56.311(2)?     "allowed": true,
I20160612-19:11:56.311(2)?     "methodName": "login",
I20160612-19:11:56.311(2)?     "methodArguments": [
I20160612-19:11:56.311(2)?       {
I20160612-19:11:56.311(2)?         "resume": "ZjObWSjOrpePGmT2CIsclEdJGnbcnEIhv52Rh5dslK0"
I20160612-19:11:56.311(2)?       }
I20160612-19:11:56.311(2)?     ],
I20160612-19:11:56.311(2)?     "user": {
I20160612-19:11:56.311(2)?       "_id": "rtMZfy2ApCsnmw9vg",
I20160612-19:11:56.311(2)?       "createdAt": "2016-01-18T15:47:39.000Z", {
...
```

Seems like it's showing data after all, at least for `INFO` level.

PS: I'm using versions `1.1.2` for `ostrio:logger` and `ostrio:loggerfile`, `1.2.0` for `ostrio:loggerconsole` and `1.1.3` for `ostrio:loggermongo`

**Comment by dr-dimitru** [comment]
> Seems like it's showing data after all, at least for INFO level.

Only if you have it, otherwise it's not shown.
I got your point now (_finally_), I'll release fix in few minutes

**Comment by dr-dimitru** [comment]
@luixal please see v1.2.1

**Comment by luixal** [comment]
We have serious understanding issues xD

Yes, this was my point all the way down. Anyway, logger is much flexible now! :)

Works like a charm now, thanks!

**Comment by dr-dimitru** [comment]
Great! Thank you for using this package. 
Do not forget to star it on both GitHub and Atmosphere (_if you didn't yet_). Or even share it on Facebook or Twitter.
