### ISSUE TITLE
Data always shows, even when empty

### ISSUE THREAD

**Issue by nunof07** [VeliovGroup/Meteor-logger-console#3]
Hi,

Thank you for this great package. I have a suggestion/issue.

The data param is always showing up on the browser console, even when it's empty, which is a bit annoying.

![image](https://cloud.githubusercontent.com/assets/13945913/18026591/4f1b38a6-6c44-11e6-905c-50276eb1e2b6.png)

The data param always gets added after the format, regardless of what you put in the format. So if you print the data in the format it will show up twice. Example:

![image](https://cloud.githubusercontent.com/assets/13945913/18026611/f1ad8a88-6c44-11e6-872f-8f5b7777b80c.png)

This is a bit of a different behavior compared to the server console where the data is only printed if you specify it directly in the format.

I actually like that the data is added to the browser console since the browser renders it nicely, but ideally I would like to have more control over this.

So my suggestions are:
1. When data is empty don't show it in the console log, that way we avoid seeing the clutter for "Object {}".
2. Add an additional setting where you can toggle it on/off completely. That way if you want to do a custom render of the data you do it in the format and can avoid it showing up twice.

**Comment by dr-dimitru** [comment]
@nunof07 thank you a lot for this contribution.
I'm sorry for more than a year delay with its delivery.
Should be solved in [`v2.0.2`](https://github.com/VeliovGroup/Meteor-logger-console/releases/tag/2.0.2)

Feel free to reopen it in case if the issue still persists on your end.

**Comment by nunof07** [comment]
Thank you for the fix. Glad I was able to contribute.
