### ISSUE TITLE
transported log always shows 'server', even if msg originates from client

### ISSUE THREAD

**Issue by edovino** [VeliovGroup/Meteor-logger-console#4]
I guess that is to be expected (since the logging of the _transported_ message does happen on the server), but can I configure the logging system so it shows the *origin* of the log event?

**Comment by dr-dimitru** [comment]
Hello @edovino ,

You're right, logging request is transferred from Client to Server.
I recommend to set caller side in `data` param:
```js
log.info('message', {
  caller: (Meteor.isServer) ? 'Server' : 'Client'
}, 'userId');
```

Let me know if it is helpful.

**Comment by edovino** [comment]
yes - that will work perfectly! I'll make a wrapper to set '`data.caller`' automatically, and use that in the `format()` function in the `LoggerConsole` adapter.
thx!

**Comment by dr-dimitru** [comment]
@edovino great, I'm glad it worked for you.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-logger)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/logger)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
