### ISSUE TITLE
Method '1_logger_emit_Console' not found

### ISSUE THREAD

**Issue by AlexanderZvyagin** [VeliovGroup/Meteor-logger-console#6]
With the code:

```
import { Logger }        from 'meteor/ostrio:logger';
import { LoggerConsole } from 'meteor/ostrio:loggerconsole';

// Initialize Logger:
const mylog = new Logger();
// Initialize and enable LoggerConsole with default settings:
(new LoggerConsole(mylog)).enable();

export function log(level,message)
{
    console.log('['+level+'] ',message);
    mylog.info('message',{},'');

}

```

I get the log message in the browser, but always with the error:

`Error invoking Method '1_logger_emit_Console': Method '1_logger_emit_Console' not found [404]`

What is wrong?!

**Comment by dr-dimitru** [comment]
Hello @WarShoe ,

This two lines:
```js
const mylog = new Logger();
(new LoggerConsole(mylog)).enable();
```

Should be executed on both *Client* and *Server*.

**Comment by AlexanderZvyagin** [comment]
Thanks!

The error is gone, the console logging looks OK (and the next step will be to use mongodb).  I am not sure about the _best practice_, but this is what I do know:

```
var mylog = {};

export function log_init() {
    mylog = new Logger();
    (new LoggerConsole(mylog)).enable();
}

// logger-neutral function, because I decide now about the logger package to use in my code
export function log(level,message,data)
{
    console.log('['+level+'] ',message,data); // just for check
    mylog[level](message,data);
}
```

log_init() is called by Meteor.startup() for server/client. Please let me know if there is a better way to init the package.

P.S. Where is it mentioned in the documentation?! Did I miss it?

**Comment by dr-dimitru** [comment]
> P.S. Where is it mentioned in the documentation?! Did I miss it?

Agree it's not obvious right now, will update the docs, thank you for this remark.
Currently, it says:

> Initialization [*Isomorphic*]

Where *Isomorphic* is meant it will work in both environments, agree it's missing some info.

> Please let me know if there is a better way to init the package.

I would place initialization to `/lib/` or `/imports/lib/` so it will be executed in both *Client* and *Server* environments.

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-logger)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/logger)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
