### ISSUE TITLE
No way to prevent info() from logging to console

### ISSUE THREAD

**Issue by chafey** [VeliovGroup/Meteor-logger-console#8]
Every time I use the info() function, it logs the arguments to console here:

https://github.com/VeliovGroup/Meteor-logger-console/blob/master/loggerconsole.js#L82

This behavior seems unusual so I suspect it was debug code left in?  If this feature is desired, can we disable it via configuration?

**Comment by dr-dimitru** [comment]
@chafey good catch. Sorry for this one. Going to fix it.

**Comment by dr-dimitru** [comment]
@chafey thank you, done in [`v2.0.3`](https://github.com/VeliovGroup/Meteor-logger-console/releases/tag/2.0.3).
Please update, and let me know how it works for you.

**Comment by chafey** [comment]
Fixed, thank you for the quick response! Starring these projects

**Comment by dr-dimitru** [comment]
@chafey thank you. I'm glad it's solved, and you've found a use in it.
